services:
  - type: web
    name: studypulse-api
    runtime: docker
    plan: free
    dockerfilePath: ./studypulse/Dockerfile
    dockerContext: ./studypulse
    envVars:
      - key: STUDYPULSE_DB_URL
        sync: false
      - key: STUDYPULSE_DB_USERNAME
        sync: false
      - key: STUDYPULSE_DB_PASSWORD
        sync: false
      - key: STUDYPULSE_JWT_SECRET
        sync: false
      - key: STUDYPULSE_CORS_ORIGINS
        sync: false
